services:
  app:
    image: sakuheinonen/stms:latest
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: stms
      DB_USERNAME: stms_user
      DB_PASSWORD: password
    container_name: stms_app
    networks:
      - stms_network
    depends_on:
      database:
        condition: service_healthy
    restart: no
  
  
  database:
    image: sakuheinonen/stms-db:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stms
      MYSQL_USER: stms_user
      MYSQL_PASSWORD: password
    ports:
      - "3306"
    networks:
      - stms_network
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb", "-u", "root", "-prootpassword", "-e", "SELECT 1;" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  stms_network:
    driver: bridge

volumes:
  mariadb_data: