version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stms_app
    environment:
      - DISPLAY=host.docker.internal:0
      - DB_HOST=mariadb
    depends_on:
      - mariadb
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stms
      MYSQL_USER: stms_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: